---
# handlers file for selinux_disable

    - name: reboot
      command: reboot
      
    - name: pause
      local_action: pause minutes=1 
      sudo: false
      
    - name: wait
      local_action: wait_for host={{ waitfor_host }} state=started port={{ waitfor_host }}
      sudo: false    

