---
# handlers file for selinux_disable

    - name: reboot
      command: reboot
      
    - name: pause
      local_action: pause seconds={{ wait_time }}
      sudo: false  

    - name: wait
      local_action: wait_for host={{ waitfor_host }} state=started port={{ waitfor_port }}
      sudo: false  



