---
# handlers file for selinux_disable

    - name: reboot
      shell: (sleep 2s;reboot)&

    - name: wait
      local_action: wait_for host={{ waitfor_host }} state=started port={{ waitfor_port }} delay=10
      sudo: false  

    - name: pause
      local_action: pause seconds={{ wait_time }}
      sudo: false  



